apiVersion: v1
kind: Service
metadata:
  name: myservice
  namespace: test
  labels:
    app: iv
spec:
  type: NodePort
  selector:
    app: iv
  ports:
    - port: 8585
      targetPort: 8585
      nodePort: 30002
